// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _1.DAL.Context;

namespace _1.DAL.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220516161531_thuyendeptraiqua")]
    partial class thuyendeptraiqua
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("_1.DAL.DomainModels.NhaSanXuat", b =>
                {
                    b.Property<Guid>("IdnhaSanXuat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDNhaSanXuat");

                    b.Property<string>("MaNhaSanXuat")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenNhaSanXuat")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("IdnhaSanXuat");

                    b.ToTable("NhaSanXuat");
                });

            modelBuilder.Entity("_1.DAL.DomainModels.Product", b =>
                {
                    b.Property<Guid>("MaHangHoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("DonGiaBan")
                        .HasColumnType("float");

                    b.Property<double>("DonGiaNhap")
                        .HasColumnType("float");

                    b.Property<Guid?>("IdnhaSanXuat")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDNhaSanXuat");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("TenHangHoa")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaHangHoa");

                    b.HasIndex("IdnhaSanXuat");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("_1.DAL.DomainModels.TestingObejct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TestingObejct");
                });

            modelBuilder.Entity("_1.DAL.DomainModels.Product", b =>
                {
                    b.HasOne("_1.DAL.DomainModels.NhaSanXuat", "IdnhaSanXuatNavigation")
                        .WithMany("Products")
                        .HasForeignKey("IdnhaSanXuat");

                    b.Navigation("IdnhaSanXuatNavigation");
                });

            modelBuilder.Entity("_1.DAL.DomainModels.NhaSanXuat", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
